### ISSUE TITLE
use streams instead of pure file for upload and download

### ISSUE THREAD

**Issue by raspher** [experimentaltvcenter/InternetArchive.NET#1]
Change
```
await archive.Item.PutAsync(new Item.PutRequest
{
    Bucket = "my-identifier",
    LocalPath = "/path/to/local/file.txt",
    RemoteFilename = "hello.txt",
    Metadata = metadata,
    CreateBucket = true
});
```

to 

```
await archive.Item.PutAsync(new Item.PutRequest
{
    Bucket = "my-identifier",
    SourceStream = File.OpenRead(),
    RemoteFilename = "hello.txt",
    Metadata = metadata,
    CreateBucket = true
});
```

In all places in library. Such small change can be a big improvement:
- For library:
  - less code, less mess to worry about
  - better flexibility
- For library consumers:
  - easier to adopt into any project, as stream sources may vary. 
  - customer applications must not write to disc, as stream can be processed directly which is an performance improvement.
  - less physical resources used to do same job

There is one drawback of such change: we require library users to implement file/stream handling on themselves, which is again an improvement, cos they know what they're doing and they do what they want to do, as library should not limit possibilities.

If it's possible, let consumers choose the stream buffer too, as it might be important in some cases. Apps for personal use would choose smaller buffer while very fast servers with 10Gbps connection speed would take bigger buffers.

Streams should be everywhere, on uploads, search results and downloads. Those results can be processed on fly while being downloaded or even without being saved to disk.

**Comment by experimentaltv** [comment]
I added this in 3.0.0. You may now specify either a ``SourceStream`` or a ``LocalPath``.

Note that streams aren't a perfect match for Internet Archive's S3-like server APIs. To support multipart (chunked) uploads the backend needs to know the total length up front. Also, the stream must be seekable. 

But it seems like this would be useful even with those restrictions. Thank you for the suggestion.
